name: Kotlin CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Run Tests
      uses: docker://zenika/kotlin:1.3-alpine
      with:
        args: sh ./scripts/kotlin-test.sh
